### ISSUE TITLE
Error with SSO

### ISSUE THREAD

**Issue by zoglesby** [flathub/us.zoom.Zoom#1]
I am trying to login to my zoom account which uses SSO and I get the following error. The part about `/home/levi/` is a bit odd

> [zoglesby@zaphod fdev]$ flatpak run us.zoom.Zoom
ZoomLauncher started.
cmd line: 
$HOME = /var/home/zoglesby 
export SSB_HOME=/var/home/zoglesby/.zoom; export QSG_INFO=1; export LD_LIBRARY_PATH=/app/extra/zoom; /app/extra/zoom/zoom "" 
zoom started.
[CZPClientLogMgr::LogClientEnvironment] [**Hardware Info Remove**][Req ID: ]
Linux Client Version is 2.0.115900.1201
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = GNOME;   GDMSESSION = gnome
Graphics Card Info:: 
Zoom package arch is 64bit, runing OS arch is x86_64
AppIconMgr::systemDesktopName log Desktop Name: gnome 
qt.scenegraph.general: QSG: basic render loop
qt.scenegraph.general: Using sg animation driver
Qt WebEngine ICU data not found at /home/levi/Qt5.9.2/5.9.2/gcc_64/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/levi/Qt5.9.2/5.9.2/gcc_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/levi/Qt5.9.2/5.9.2/gcc_64/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine resources not found at /home/levi/Qt5.9.2/5.9.2/gcc_64/resources. Trying parent directory...
Qt WebEngine resources not found at /home/levi/Qt5.9.2/5.9.2/gcc_64. Trying application directory...
Qt WebEngine ICU data not found at /home/levi/Qt5.9.2/5.9.2/gcc_64/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/levi/Qt5.9.2/5.9.2/gcc_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/levi/Qt5.9.2/5.9.2/gcc_64/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine resources not found at /home/levi/Qt5.9.2/5.9.2/gcc_64/resources. Trying parent directory...
Qt WebEngine resources not found at /home/levi/Qt5.9.2/5.9.2/gcc_64. Trying application directory...
[5:70:0210/204144.468235:FATAL:udev_loader.cc(38)] Check failed: false. 
#0 0x7f41f2b36b2e <unknown>
#1 0x7f41f2b4883e <unknown>
#2 0x7f41f23d4e6f <unknown>
#3 0x7f41f23d3f59 <unknown>
#4 0x7f41f23d4a6f <unknown>
#5 0x7f41f36893a8 <unknown>
#6 0x7f41f2bac3f9 <unknown>
#7 0x7f41f2b50d70 <unknown>
#8 0x7f41f2b529ad <unknown>
#9 0x7f41f2b52e65 <unknown>
#10 0x7f41f2b54300 <unknown>
#11 0x7f41f2b4fe92 <unknown>
#12 0x7f41f2b6c5ca <unknown>
#13 0x7f41f2470a05 <unknown>
#14 0x7f41f2470e63 <unknown>
#15 0x7f41f2b84490 <unknown>
#16 0x7f41f2b807ad <unknown>
#17 0x003bd8207444 <unknown>
#18 0x003bd7ae827f <unknown>

**Comment by nedrichards** [comment]
udev_loader is an interesting fail. I can add udev to the build and see if that helps but don't have access to Zoom SSO to test myself.

**Comment by nedrichards** [comment]
When the update is available can you test again?

**Comment by zoglesby** [comment]
Sure can.

**Comment by zoglesby** [comment]
I am sorry, I missed the updates to this. I have now tested this and it is fixed. Thanks.
