### ISSUE TITLE
sha256sum is wrong because of new zoom release 2.4.121350.0816

### ISSUE THREAD

**Issue by ankurs47** [flathub/us.zoom.Zoom#13]
While installing zoom, it gives following error, because of new zoom release.

```
flatpak install flathub us.zoom.Zoom
Installing in system:
us.zoom.Zoom/x86_64/stable flathub 03b6d1b80b58
  permissions: ipc, network, pulseaudio, x11, devices
  file access: home
Is this ok [y/n]: y
Installing: us.zoom.Zoom/x86_64/stable from flathub
[####################] Downloading files: 1/1 65.4 MB (65.4 MB/s)         
error: Failed to install us.zoom.Zoom/x86_64/stable: Wrong size for extra data https://zoom.us/client/latest/zoom_x86_64.tar.xz
```

Also consider using version specific urls in us.zoom.Zoom.json (https://zoom.us/client/2.4.121350.0816/zoom_x86_64.pkg.tar.xz), so that this will not happen in the future

**Comment by nedrichards** [comment]
Thanks for a link to the persistent directory, I wasn't aware of those.

**Comment by nedrichards** [comment]
Fixed by https://github.com/flathub/us.zoom.Zoom/commit/5f2bd0ebe2f1e3da43228d83a8a2eea1013b9012 (when built and updated)
