### ISSUE TITLE
Missing tray icon

### ISSUE THREAD

**Issue by BjoernDaase** [flathub/us.zoom.Zoom#144]
* Fedora 32
* Gnome 3.36.0
* Wayland

When using the rpm directly, zoom has a tray icon. The tray icon is not there when using the flatpak version.

**Comment by ids1024** [comment]
This is probably due to the flatpak apparently only supporting XOrg, so it is probably running through XWayland (https://github.com/flathub/us.zoom.Zoom/issues/24).
