### ISSUE TITLE
Update to new version: 2.4.129780.0915

### ISSUE THREAD

**Issue by kat-co** [flathub/us.zoom.Zoom#15]

**Comment by dsd** [comment]
Still pending, is anyone working on this?
Direct link to new version is https://zoom.us/client/2.4.129780.0915/zoom_x86_64.tar.xz

**Comment by nedrichards** [comment]
Should be fixed by https://github.com/flathub/us.zoom.Zoom/commit/f3304a999cef2b9c4c7c6d3f590f671d4ed842b3
