### ISSUE TITLE
Could not connect to any X display

### ISSUE THREAD

**Issue by heftig** [flathub/us.zoom.Zoom#160]
As of the latest update:

```
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```

**Comment by heftig** [comment]
Zoom does not support Wayland. There's no point in exposing Wayland to it. And if you withhold the X11 socket (by using `fallback-x11`) it won't work at all.

**Comment by alatiera** [comment]
as a temporary workaround, so you dont have to downgrade, you can launch it with `--nosocket=wayland` or add a more permanent override which should make the desktop launcher also work.

```
flatpak run --nosocket=wayland us.zoom.Zoom
# flatpak override --nosocket wayland us.zoom.Zoom
```
