### ISSUE TITLE
SSO login does not work

### ISSUE THREAD

**Issue by amarshall** [flathub/us.zoom.Zoom#176]
This appears different than #169.

### Reproduction

1. Open Zoom
2. Sign in with SSO (enter valid SSO domain and press Continue)
3. Nothing happens, no SSO login opens anywhere, regardless of the value of `embeddedBrowserForSSOLogin` in `zoomus.conf`.

### Logs

In Zoom stdout:

> QProcess: Destroyed while process ("./zopen") is still running.

In journalctl:
> xdg-desktop-portal: Error: no DISPLAY environment variable specified

### Relevant abbreviated system information

Fedora 32, Kernel 5.6.8, Flatpak 1.6.3, SwayWM

From `flatpak info us.zoom.Zoom`:
ID: us.zoom.Zoom
Ref: app/us.zoom.Zoom/x86_64/stable
Arch: x86_64
Branch: stable
Version: 5.0.399860.0429
Origin: flathub
Collection: org.flathub.Stable
Installation: system
Runtime: org.freedesktop.Platform/x86_64/19.08
Sdk: org.freedesktop.Sdk/x86_64/19.08
Commit: 6daab69e533295b835228101758846939caecf451a5f1be4aa1b5a1ae53d756c
Parent: 675bdb2007ef0c4931df5a11249c1912483bfcca6254e7e530d0d5b5556fad35
Subject: Update zoom.tar.xz to 5.0.399860.0429 (98c53c43)
Date: 2020-04-30 12:19:10 +0000

**Comment by klardotsh** [comment]
Exact same issue here on Void x86_64-musl, kernel 5.6.11, flatpak 1.6.3, Sway. Logging in by email+password works fine.

**Comment by amarshall** [comment]
This started working for me. My best guess is that it’s because I changing to running Sway via `dbus-run-session` (which I did to resolve a different problem unrelated to Zoom), but I’m hesitant to test since it would require logging-out and carefully backing-up things as I don’t want to be unable to log back in. But maybe you can try that @klardotsh ?

**Comment by amarshall** [comment]
Closing since I no longer have this issue, will reopen if it happens again.

**Comment by samueltwallace** [comment]
I'll bump this since I am having a nearly identical problem. I am running Void x86_64-musl 5.4.50, but not sway. I'm on Xorg + bspwm, and flatpak 1.6.3. Whenevery I click anything from the signin page (SSO, Google login, etc.) I get the error in stdout:

```
QProcess: Destroyed while process ("./zopen") is still running.
Failed to connect to session bus: Error spawning command line ?dbus-launch --autolaunch=b04b8ebc32f1013034e621435f0274af --binary-syntax --close-stderr?: Child process exited with code 1success to create child process,status is 2.
```

And I have no idea what this means.

**Comment by sedrubal** [comment]
```bash
systemctl --user restart xdg-desktop-portal.service
```

fixes it for me.

**Comment by mvdan** [comment]
To add to what @sedrubal just said: if you're on Sway, you need to install both xdg-desktop-portal-wlr and xdg-desktop-portal-gtk, and then restart the systemctl service -- or the entire machine. Links just won't work without the GTK portal installed.
