### ISSUE TITLE
Why does Zoom need full rw access to my home directory?

### ISSUE THREAD

**Issue by Mikaela** [flathub/us.zoom.Zoom#18]
* https://github.com/flathub/us.zoom.Zoom/blob/f3304a999cef2b9c4c7c6d3f590f671d4ed842b3/us.zoom.Zoom.json#L13

I am new user to Zoom, my organisation decided to require it for remote attendance and I was happy to see it in Flathub. However the filesystem access hit my eyes and I don't see why it wants that wide filesystem access. Could it work with less access?

**Comment by booxter** [comment]
In addition to file sharing, zoom also dumps recorded calls to homedir.

**Comment by nanonyme** [comment]
https://github.com/flathub/us.zoom.Zoom/pull/143 is planning to reduce the access in order to land some fixes

**Comment by laolux** [comment]
I have it working without access to my entire home directory. Remove permissions with `flatpak --user override --nofilesystem home us.zoom.Zoom`. This will also revoke read access to the home directory, which would still be allowed in #146 .

Next, allow zoom to write to `~/Documents/Zoom`, as it seems to save recordings there by default: `flatpak override --filesystem xdg-documents/Zoom us.zoom.Zoom`.

**Comment by davide-trellis** [comment]
I'm pretty new to flatpak, and needing Zoom for work, I went with the Flatpak version. I wanted to lock down filesystem access, found the previous comment, but it has a minor bug, missing "--user"  parameter. So I ended up with these 3 statements: 

`flatpak override  --user --nofilesystem home us.zoom.Zoom`
`flatpak override  --user --filesystem xdg-documents/Zoom us.zoom.Zoom`

Then, since I don't want to enter my zoom password all the time, I gave it access to its config:

`flatpak override  --user --filesystem ~/.zoom us.zoom.Zoom`

**Comment by WhyNotHugo** [comment]
@davide-trellis You can also tell flatpak to persist its config without it littering your home directory:

```
flatpak override --user --persist=.zoom --persist=.config us.zoom.Zoom
```

**Comment by toMeloos** [comment]
One thing that should be fixed so its RW access to the entire home directory can be revoked is to map the configuration to the right directory. It seems like Zoom is storing its config in `~/.zoom`, which is undesirable even for local installations (`~/.config/zoom` is preferred). So a bind mount is required to map `~/.var/app/us.zoom.Zoom/config` or `~/.var/app/us.zoom.Zoom/data` to `~/.zoom` inside the flatpak container, in stead of the entire host home directory. 

I know how to do this in Docker, but does Flatpak also offer this feature?

**Comment by WhyNotHugo** [comment]
@toMeloos See #146

**Comment by TheEvilSkeleton** [comment]
Feel free to close this issue; it got fixed: https://github.com/flathub/us.zoom.Zoom/pull/199
