### ISSUE TITLE
(Re)-asks for login every time.

### ISSUE THREAD

**Issue by codic12** [flathub/us.zoom.Zoom#181]
Hi! I'm on Solus KDE X11 using the Zoom flatpak. It works awesome, except when I log in (with google), on next boot (not next start of the application, even if I kill from system tray), it will re ask for login. I can press sign in with google though, and then it doesn't even ask for credentials - just logs me in straightaway. I want to be always logged in as was the case when I was using the arch package on Manjaro. Any ideas? Thank you in advance!

**Comment by juliengs** [comment]
Same issue on Fedora 32. Username and password fields seem to contain "garbage" data; e.g., the username field contains a very long string of alphanumeric characters -- I need to remove these and replace with proper credentials.

Note: I had the real non-flatpak version of Zoom installed before (I had removed it) so I'm not sure if it can be related.

**Comment by codic12** [comment]
I realized this happens with the non-flatpak version of zoom too on all distros, so is an upstream bug. closing therefore.
