### ISSUE TITLE
There's no i386 package

### ISSUE THREAD

**Issue by ChMaille** [flathub/us.zoom.Zoom#193]
I everybody !
There no i386 version of Zoom in Flatpak. On the official website, there's a .deb package in x64 and i386.
When the i386 will be done please ?

**Comment by nedrichards** [comment]
There are no i386 runtimes available for the 19.08 freedesktop runtime and newer (per https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/19.08/NEWS ) so this can't be provided under a supported platform I'm afraid.

**Comment by ishmartbuoy** [comment]
Is it feasible to use Freedesktop SDK 1.6 runtime to build the i386 version of Zoom in Flatpak ?
