### ISSUE TITLE
Zoom doesn't start on NVIDIA video, installing NVIDIA runtime fixes the issue

### ISSUE THREAD

**Issue by develop7** [flathub/us.zoom.Zoom#2]
Guess it should depend on NVIDIA runtime

**Comment by TingPing** [comment]
The nvidia drivers are automatically installed already. Any problem you had is probably due to something like an outdated gnome-software or such if I had to guess.

**Comment by develop7** [comment]
@TingPing my bad, I meant proprietary NVIDIA driver v390.42. Flathub repository had nvidia runtime v390.25 only on the day before the issue was filed, which I've installed, but the issue persisted; next day I've ran `flatpak update`, it has installed nvidia runtime v390.42, I've tried to run Zoom again, and it worked like a charm.
