### ISSUE TITLE
Cannot find saved recordings

### ISSUE THREAD

**Issue by twoertwein** [flathub/us.zoom.Zoom#228]
Since this PR https://github.com/flathub/us.zoom.Zoom/pull/199 I can no longer find my saved recordings. Zoom saves them in `~/Documents/Zoom`. When I ask zoom to open a file open dialogue where to save the recording, it defaults to that folder but its content is different from the real `~/Documents/Zoom`. I wasn't able to find the created files anywhere in` /var/flatpack` nor anywhere in my home directory.

**Comment by TheEvilSkeleton** [comment]
That's really weird, because it works fine for me. Have you tried using the beta version instead? There has been a change in the permissions in the beta version, so you could try that and keep me updated.

**Comment by twoertwein** [comment]
sorry, it worked after re-installing zoom.
