### ISSUE TITLE
Unable to join in latest version

### ISSUE THREAD

**Issue by edent** [flathub/us.zoom.Zoom#238]
Not sure how to debug this. I see that I am "waiting to be let in" - but when I'm eventually let in, I just get a "connecting" spinner. After a few minutes it still doesn't connect. I've tried on Wayland and Gnome sessions.

If I install the DEB directly, I can connect to my meetings without issue.

* Zoom version 5.4.3 (54779.1115)
* Pop OS 20.10

**Comment by muelli** [comment]
sounds like https://github.com/flathub/us.zoom.Zoom/issues/289

**Comment by muelli** [comment]
eh, I meant https://github.com/flathub/us.zoom.Zoom/issues/285

**Comment by muelli** [comment]
let me close in favour of #285
