### ISSUE TITLE
Zoom should use  $XDG_DOCUMENTS_DIR/Zoom instead of ~/Documents/Zoom for recordings.

### ISSUE THREAD

**Issue by ieugen** [flathub/us.zoom.Zoom#254]
Hi,

I use my localized desktop and it would be nice if Zoom used the XDG_DOCUMENTS_DIR for saving recordings, like a well behaved app :) . 

See more details here https://wiki.archlinux.org/index.php/XDG_user_directories

**Comment by TheEvilSkeleton** [comment]
Are you sure? A couple of months ago there was this https://github.com/flathub/us.zoom.Zoom/issues/208.

**Comment by ieugen** [comment]
Hi, 

Yes, @208 is reporting the exact same issue. 
I am using Romanian and I have `~/Documente` but zoom uses `~/Documents` . 
See `xdg-user-dir DOCUMENTS` as described in https://wiki.archlinux.org/index.php/XDG_user_directories .

```
xdg-user-dir DOCUMENTS
/home/ieugen/Documente
```

In order to make make apps play well with localized environments, FreeDesktop made the XDG Base Directory Specification https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html  .

For each common directory (like Documents) there is an environment variable that tells you what it is so it's not hard coded. 
See also https://docs.flatpak.org/en/latest/conventions.html#xdg-base-directories . 

I believe zoom should use `XDG_DOCUMENTS_DIR` if it is defined and then fallback for hardcoded `~/Documents` path. 

In bash you can use a default value for a variable, something like this might work: `my_dir=${XDG_DOCUMENTS_DIR:-$HOME/Documents}`


To me, the name for #216 is misleading / not descriptive of what the commit does: 
![Captură de ecran de la 2021-02-21 18-06-52](https://user-images.githubusercontent.com/1050920/108630865-bada6980-746f-11eb-9f18-c15563081d2f.png)

**Comment by TheEvilSkeleton** [comment]
I'm aware of what XDG directories are, but from an earlier report (https://github.com/flathub/us.zoom.Zoom/issues/208), Zoom **does not** use XDG directories, but **hardcodes** `~/Documents/Zoom` instead.

> In bash you can use a default value for a variable, something like this might work: `my_dir=${XDG_DOCUMENTS_DIR:-$HOME/Documents}`

You might want to submit a PR because I don't know much of bash.

> To me, the name for #216 is misleading / not descriptive of what the commit does:

This commit was a fix to #208.

**Comment by ieugen** [comment]
I see now, so this should be reported to Zoom actually. 
I did try but it's very difficult to report anything if you don't have a payed subscription. 

So I guess without upstream support this won't be easy to fix. 

Thanks for looking into this.
