### ISSUE TITLE
setxkbmap is missing

### ISSUE THREAD

**Issue by vincentbernat** [flathub/us.zoom.Zoom#26]
Hey!

When I try to share my screen, Zoom wants to use setxkbmap to configure the keyboard. As it is not included in Flatpak, I get:

```
sh: setxkbmap: command not found
sh: ibus: command not found
sh: setxkbmap: command not found
sh: ibus: command not found
sh: ibus: command not found
sh: ibus: command not found
sh: setxkbmap: command not found
sh: ibus: command not found
sh: ibus: command not found
sh: ibus: command not found
```

I suspect this is the cause on why some of my keys are not mapped correctly. Would it be possible to include setxkbmap?

Thanks.

**Comment by muelli** [comment]
I guess yes. Although it feels a little weird to configure your keyboard from within the app.
Do you know which tarball to build in order to get that binary?

**Comment by vincentbernat** [comment]
It's available here: https://xorg.freedesktop.org/releases/individual/app/setxkbmap-1.3.2.tar.gz

However, I think Zoom did another change as I didn't have a keyboard problem since quite some time. So, unless someone run into this problem, I suggest we just close this issue.

**Comment by muelli** [comment]
okay :)
