### ISSUE TITLE
Error: Invalid Exec argument @@u when trying to update

### ISSUE THREAD

**Issue by networkException** [flathub/us.zoom.Zoom#272]
Hello, for a few days now I have been getting the following output when running `flatpak update`

```
Looking for updates…


        ID                   Branch         Op        Remote         Download
 1. [✗] us.zoom.Zoom         stable         u         flathub        51.7 MB / 51.8 MB

Error: Invalid Exec argument @@u
Updates complete.
error: There were one or more errors
```

I'm sorry if the issue is not related to the Zoom packaging, a bump in the right directory to investigate the problem would help as well.

**Comment by vchernin** [comment]
`Error: Invalid Exec argument @@u`
It sounds like it's probably something misconfigured in your environment.
Can you try uninstalling and reinstalling zoom flatpak?

Also perhaps try uninstalling and reinstalling flatpak. 

If that doesn't work, try see what's in zoom's .desktop file, especially the `Exec=` line.
`cat /var/lib/flatpak/app/us.zoom.Zoom/current/active/files/share/applications/us.zoom.Zoom.desktop`

Ensure there's nothing overriding zoom's .desktop file in `~/.local/share/applications`

**Comment by networkException** [comment]
No clue what this was but reinstalling worked
