### ISSUE TITLE
Package on Flathub outdated / not in sync with this github repo

### ISSUE THREAD

**Issue by stendler** [flathub/us.zoom.Zoom#274]
The package version on [flathub](https://flathub.org/apps/details/us.zoom.Zoom) is still `5.6.20278.0524` while the latest version in this repo is `5.6.22045.0607` even though the [latest(?) test build succeeded](https://flathub.org/builds/#/builders/19/builds/5919).

A [manual local build](https://docs.flatpak.org/en/latest/first-build.html) with the following commands was successful.

```sh
mkdir build
flatpak install flathub org.freedesktop.Sdk//20.08 # install dependency - may require sudo
flatpak-builder --user --install --from-git=https://github.com/flathub/us.zoom.Zoom.git build us.zoom.Zoom.json
rm -rf build
```

**Comment by vchernin** [comment]
It appears that there was indeed a failed build for Zoom Flatpak master.

The buildbot page for Zoom [doesn't list any recent failed builds](https://flathub.org/builds/#/apps/us.zoom.Zoom).

However, [on the page for all Flatpaks](https://flathub.org/builds/#/apps) you can see the most recent Zoom build failed.

[Build 50329](https://flathub.org/builds/#/builders/32/builds/50329) appears to have failed, and that happened around the time that new version was released (the new zoom release was around June 7th per the version name `.0607`.

Build 50329's failure should be investigated. Or is there a simple way to trigger buildbot to try again?

**Comment by vchernin** [comment]
@muelli Since you merged #273, could you try to [rebuild 50329](https://flathub.org/builds/#/builders/32/builds/50329)? That might resolve the issue as I haven't found any other recent failing builds. ([this idea was suggested on matrix](https://matrix.to/#/!RfXaBjokqHAbzZrgHz:matrix.org/$sH4M9UdzOfjaMFMW8VcgptfxX_JzmINZAkf4z6-4Vag?via=matrix.org&via=gnome.org&via=kde.org))

**Comment by muelli** [comment]
https://flathub.org/builds/#/builders/32/builds/51155

**Comment by vchernin** [comment]
Latest build is now available on Flathub stable, thanks @muelli for rebuilding and @stendler for reporting the issue!

**Comment by stendler** [comment]
@vchernin thanks for getting to the bottom of this issue. Hopefully some measures will be implemented to prevent similar issues in the future.
