### ISSUE TITLE
Impossible to connect: Zoom wants version 5.8

### ISSUE THREAD

**Issue by julienlarena** [flathub/us.zoom.Zoom#289]
I am running the Flatpak wrapper on POP OS and since last week, I cannot connect to Zoom via the desktop app as it says:

 Update required

Your app version needs to be 5.8.0 (16) or higher to sign in.
Please update to continue

Connection directly via the browser works fine so it is not a problem with my account.
Any idea of what is going on?
Thanks!

**Comment by muelli** [comment]
My wild guess is that it requires a newer version than what you have installed.

https://github.com/flathub/us.zoom.Zoom/pull/286 or https://github.com/flathub/us.zoom.Zoom/pull/288 are about newer versions.

**Comment by julienlarena** [comment]
Yes, I figured. I just find it strange that it has never happened before. 
The version I have installed is the one available on the package  manager for my distro. I guess I'll have to wait for 5.8 to get pushed.
