### ISSUE TITLE
(web) Microphone is recognized but doesn't send audio

### ISSUE THREAD

**Issue by Zeioth** [flathub/us.zoom.Zoom#290]
* OS: Manjaro-
* Browser: Firefox and Chrome

On my audio panel (pavucontrol) the microphone gets audio.

https://x0.at/uqag.png

I accept the permissions on Firefox and Zoom lists the microphone name fine.

https://x0.at/aV83.png

But it doesn't work. Every other web work with my microphone except Zoom.

Any idea why?

**Comment by 4ndyZ** [comment]
This repo is not the official Zoom client/web repository. This repository is for the community driven flatpak package of Zoom.

Please contact the Zoom support with your problem. They may be able to help you.

**Comment by Zeioth** [comment]
It seem Zoom fixed it (Firefox 94, zoom web version). It's the only place where I finally have all 3, image, audio, and screen sharing working. Sadly, it's a bit late, as it impacted my communications with the team during several weeks.

I'm closing this issue. Thank you.
