### ISSUE TITLE
.gmail and .googlemail

### ISSUE THREAD

**Issue by bill-chadwick** [flathub/us.zoom.Zoom#294]
Those of us with fairly old GMail accounts may well have their google account bound to .googlemail but now exclusively use .gmail for send and receive of email. Google treats the two email addresses as one and the same. 

I can't log in to my Zoom account (registered as .gmail) using google login because it tries to log me in as .googlemail. 

Could Zoom please make .gmail and .googlemail logins be equivalent, as some other service providers do.

Thanks.

**Comment by 4ndyZ** [comment]
This problem is not related to the Flatpak wrapper of Zoom. Please not that this wrapper is not verified by, affiliated with, or supported by zoom.us.

Please open up a ticket at Zoom.
