### ISSUE TITLE
Flathub Screenshots

### ISSUE THREAD

**Issue by Byrdg** [flathub/us.zoom.Zoom#295]
Hey, I have these screenshots (attached) that I think are better than the current one because they are more updated and align more on how the app looks now. If its OK to update them, can you please point me to the appdata XML source or update them?"
![img-modernizemeeting_69f1e3a](https://user-images.githubusercontent.com/94136706/141365822-a7572ce2-1ccc-422d-91aa-7b63c5f15b2d.png)
<img width="375" alt="Zoom 1" src="https://user-images.githubusercontent.com/94136706/141365906-a8bacbac-ce2a-4dbd-82d0-a99406230e8f.png">

**Comment by muelli** [comment]
the screenshot is taken from the Zoom page, as can be seen here: https://github.com/flathub/us.zoom.Zoom/blob/0fd4409eee00305b33a3b212144190d38427e482/us.zoom.Zoom.appdata.xml#L23
You can propose updates to that URL or even add new screenshots :)
