### ISSUE TITLE
Error installing on Linux Mint

### ISSUE THREAD

**Issue by christianmtr** [flathub/us.zoom.Zoom#3]
I'm trying to install Zoom on Linux Mint 18.3 with:
`sudo flatpak install flathub us.zoom.Zoom`
but I get this error:
```
Instalando: us.zoom.Zoom/x86_64/stable desde flathub
[################### ] Downloading: 64,6 MB/67,0 MB (680,4 kB/s)               
error: Tamaño incorrecto en los datos adicionales https://zoom.us/client/latest/zoom_x86_64.tar.xz
```
or `Incorrect size in the additional data` in english.

**Comment by nedrichards** [comment]
Should be fixed by https://github.com/flathub/us.zoom.Zoom/commit/0b74aab141598057b0e564bb48d6730e2ef4af61 thanks for the report.

**Comment by christianmtr** [comment]
Yes, it's fixed.
Thanks!
