### ISSUE TITLE
zoom-flatpak gets regularily useless

### ISSUE THREAD

**Issue by Akira25** [flathub/us.zoom.Zoom#305]
When I first discoverd that there is a flatpak for the zoom app, this was my first preference for installing that app for severla reasons. Sadly, I cannot use the flatpak anymore in my production-environment, as they outdate too often.

Theres even a bot, that creates a new merge-request, once there is a new zoom-version available (which apparently happens more often than other people change their underwear). As those PRs doesn't get merged by time, inresult the version in the flatpaks gets outdated.

I hope in that there might be improvement in the future, but for now, I cannot accept this anymore. I must change to another, more up-to-date packageformat. :(

**Comment by nedrichards** [comment]
Thanks - there's been enough brokenness in the updates that automatic merging isn't a good stance either. The better solution would be for Zoom themselves to take over and distribute the flatpak themselves.
