### ISSUE TITLE
Zoom freezes spontaneously

### ISSUE THREAD

**Issue by DuckDuckWhale** [flathub/us.zoom.Zoom#311]
After some time in a meeting the screen would freeze and all UI actions won't update. A "not responding" dialog pops up but the audio input and output still works. And sometimes when launching it would take a good while (1 minute or infinity) for a click to respond.

Using Ubuntu 21.10 Gnome and Wayland on Nvidia/Intel hybrid graphics.

**Comment by nedrichards** [comment]
Can you confirm if this is still an issue with 5.10 once https://github.com/flathub/us.zoom.Zoom/commit/36008f3b678d71f2c7d121259006ae9ca31d94df is available? But other than that I don't believe this is something we can influence on the flatpak side.
