### ISSUE TITLE
Application not starting after update

### ISSUE THREAD

**Issue by Taulim** [flathub/us.zoom.Zoom#315]
After the update 5.10.0.2450 (#314) the application is not starting.
No errors are visible from verbose command:

![image](https://user-images.githubusercontent.com/7851440/159470950-ca9ef50c-33fc-48db-8b22-3acaefee1f17.png)

**Comment by Taulim** [comment]
zoom_stdout_stderr.log:

```
ZoomLauncher started.
Zoom path is: /app/extra/zoom
cmd line: 
Start subprocess: /app/extra/zoom/zoom sucessfully,  process pid: 3 
Can't load/home/<user>/.config/zoomus.conf
Failed to create secure directory (/run/user/1000/pulse): Too many levels of symbolic links
No PulseAudio daemon running, or not running as session daemon.
                             Class      App      Lib Possible Culprit Flags
                resip::Connection      648      648 
                      resip::Data       36       36 
                 resip::DnsResult     1080     1080 
                   resip::Headers        1        1 
          resip::MsgHeaderScanner       40       40 
                resip::SipMessage     5208     5208 
         resip::TransportSelector      864      864 
                     resip::Tuple      128      128 
              resip::UdpTransport     1144     1144 
          resip::GenericIPAddress       28       28 

zoom started.
[0322/112808.314926:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/extra/zoom/cef/chrome-sandbox is owned by root and has mode 4755.
Failed to create secure directory (/run/user/1000/pulse): Too many levels of symbolic links
No PulseAudio daemon running, or not running as session daemon.
                             Class      App      Lib Possible Culprit Flags
                resip::Connection      648      648 
                      resip::Data       36       36 
                 resip::DnsResult     1080     1080 
                   resip::Headers        1        1 
          resip::MsgHeaderScanner       40       40 
                resip::SipMessage     5208     5208 
         resip::TransportSelector      864      864 
                     resip::Tuple      128      128 
              resip::UdpTransport     1144     1144 
          resip::GenericIPAddress       28       28 

zoom started.
zoom was exited due to a handled signal: 5 
ZoomLauncher exit.
```

**Comment by muelli** [comment]
thanks for digging up the log.
I've reverted the update.

**Comment by muelli** [comment]
and sorry for having broken it in the first place.

**Comment by lsolano** [comment]
Same thing here @muelli , hope to get the new and fixed version after coming out the beta branch. 

For not so experienced users of Flatpak, as I'm, I was able to revert to the stable version doing exactly as @ieugen: Search for the commit for version `5.9.6.2225` and then use `flatpak update` with `--commit` flag.

**Comment by barthalion** [comment]
It's definitely pointing to the revert commit right now on my end:

```
    Commit: 972052877d97e307ba6ef722172d742331ef9f4dc868a31af8b7906d1f644237
    Parent: c82bfaaa1e765d92037e64f496836cae99413f979945faef9ce20fe9f9a3bb03
   Subject: Revert Zoom 5.10.0.2450 as it doesn't start (18b07075)
      Date: 2022-03-22 11:47:13 +0000
```

Sometimes it takes a while for publishing to happen if a runtime is being pushed at the same time. I assume this was the case here.

**Comment by Taulim** [comment]
As this issue has been resolved by reverting the update, I'm closing the issue.

**Comment by ahoermann** [comment]
Would you mind reopening this issue? My organization requires version 5.10.0 (2450) even for joining meetings, so reverting the update does not help. Unfortunately, I don't have expertise in this area, so any attempt to fix it myself would probably take longer than waiting for the next release. 
If you prefer, I can open a new issue referencing this one instead.

**Comment by zroug** [comment]
I also think reverting the version isn't a fix. It is temporary workaround until a solution is found and the issue should still be open.

I suspect this issue has something to do with a web view that Zoom is using, as the `SUID` error is similar to that of flatpaked electron applications. In fact, when launching the broken Zoom Flatpak with the flag `--no-sandbox`, it works just fine. However this is not a solution because this does not work when another flag is added. I think something like https://github.com/refi64/zypak could be required.
