### ISSUE TITLE
Update to 5.10.0 workarounds

### ISSUE THREAD

**Issue by clonejo** [flathub/us.zoom.Zoom#316]
This flatpak was updated to 5.10.0 in df4e8c7f3d6af88638d78de2e4d9ddb4d0e9b28a (#314), but reverted in 18b0707592d13f37cfc1c2dc58cd102d59fb214d.

The cause seems to be the issue described in the comments of the AUR package:

* GreenAvocado commented on [2022-03-30 15:05 (UTC)](https://aur.archlinux.org/packages/zoom#comment-858961) (edited on 2022-03-30 15:05 (UTC) by [GreenAvocado](https://aur.archlinux.org/account/GreenAvocado))

  > @rosekunkel it seems to be a problem with the sandbox, which refuses to run if it is not SUID root. I was able to get Zoom to launch using the --no-sandbox option, but I had problems getting links to open in Zoom still.
  >
  > You can probably also fix it by changing the sandbox binary to be SUID root, which is probably the better solution here.

* rosekunkel commented on [2022-03-31 00:22 (UTC)](https://aur.archlinux.org/packages/zoom#comment-859041)

  > @GreenAvocado thanks for your help. Making the sandbox binary SUID seems to have fixed it:
  >
  > $ sudo chmod u+s /opt/zoom/cef/chrome-sandbox

I can confirm the `--no-sandbox` workaround works.

I don't know how Flatpak's sandboxing works, so i'm not so sure about the SUID method.

**Comment by zroug** [comment]
I made similar observations here in https://github.com/flathub/us.zoom.Zoom/issues/315#issuecomment-1085923919. Maybe we can look at how Electron applications solve this issue with https://github.com/refi64/zypak.

**Comment by nedrichards** [comment]
Gone with the workaround after the most obvious way of using zypak didn't work https://github.com/flathub/us.zoom.Zoom/commit/36008f3b678d71f2c7d121259006ae9ca31d94df thanks for the report and useful notes.
