### ISSUE TITLE
Window transparent

### ISSUE THREAD

**Issue by nicokimmel** [flathub/us.zoom.Zoom#319]
When I open Zoom its just a transparent window. When I resize it it gets black.
Im on Arch, Nvidia 510, Zen Kernel, Gnome 42, Wayland.

Working fine on X11. Already tested `QT_QPA_PLATFORM=wayland` and `QT_QPA_PLATFORM=xcb`.

Textboxes etc can be targeted, but are just not displayed.

![grafik](https://user-images.githubusercontent.com/31391271/163757802-3d8d7e52-6265-4dbf-9e7f-a4b7bc0b1740.png)
![grafik](https://user-images.githubusercontent.com/31391271/163757549-65b18396-9d2f-4d2e-9a07-94186a8a3073.png)
(Ignore my Isaac wallpaper :grimacing:)

**Comment by nedrichards** [comment]
Can you test again with 5.10.x once https://github.com/flathub/us.zoom.Zoom/commit/36008f3b678d71f2c7d121259006ae9ca31d94df gets to you? Please reopen if it's still present.

**Comment by nicokimmel** [comment]
Tested with 5.10.4.2845 from
```flatpak install --user https://dl.flathub.org/build-repo/86694/us.zoom.Zoom.flatpakref```
but it didnt change anything, window is still transparent.

![grafik](https://user-images.githubusercontent.com/31391271/165976160-a7dedc48-ed51-4f99-a0da-4c65aea8924c.png)

**Comment by excieve** [comment]
Same here with Nvidia 515 and Zoom 5.11. At the same time this just results in an immediate crash:
```
flatpak run --env="QT_QPA_PLATFORM=wayland" us.zoom.Zoom
```

The transparent main window issue is partially resolved by setting this in the Zoom conf:
```
enableAlphaBuffer=false
```

However, during the screen-sharing all the controls are black as well as in some other places.

**Comment by JPLeBreton** [comment]
I'm seeing this same issue on my Nvidia + Manjaro system with the latest GNOME, latest drivers, in Wayland. Issue does not appear when I launch Zoom in X11. Launching with different settings for QT_QPA_PLATFORM doesn't fix it.

**Comment by hugoamvieira** [comment]
Update: I've recently changed to an AMD GPU, and the flatpak version of Zoom runs great, under X or Wayland, so it seems to be an Nvidia problem.

**Comment by nicokimmel** [comment]
As always..  
Its time to switch when they release their new GPUs in Q4.

**Comment by excieve** [comment]
OK, I managed to "fix" it. In a silly way though. It looks like the issue is with the version of Qt that Zoom is shipping.

For the `xcb` mode — remove the `xcbglintegrations/libqxcb-glx-integration.so` lib in the Zoom distro and replace it with the same lib in your system's Qt5, e.g. like this on Fedora:
```
sudo ln -s /usr/lib64/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
```

No transparent/black windows anymore! Everything appears to be working, including screen-sharing. No need to disable alpha either.

For the `wayland` mode — remove the `wayland-graphics-integration-client/libqt-plugin-wayland-egl.so` and replace like this:
```
sudo ln -s /usr/lib64/qt5/plugins/wayland-graphics-integration-client/libqt-plugin-wayland-egl.so
```

Zoom doesn't crash anymore and appears to work, but there are no window decorations for me.

My system's Qt5 version is: 5.13.2, while Zoom seems to be using 5.12.10 so once they upgrade it should just work.

**Comment by JPLeBreton** [comment]
This issue is still happening and should not have been closed. The workaround excieve describes above will break any time the flatpak updates.

If this is caused by Zoom using an old version of Qt, are they aware of this issue? (It happens with the non-flatpak version.)

**Comment by JPLeBreton** [comment]
I found this thread on the Zoom support forums about this same set of issues, it hasn't been officially acknowledged yet by their support staff though so it's unclear if a fix is coming:
https://community.zoom.com/t5/Meetings/Linux-Regarding-Nvidia-Xwayland-Wayland/m-p/72922/thread-id/39702

**Comment by Laminaat** [comment]
This problem still persists on Fedora 36 with the flatpak version from flathub. Zoom 5.12.2, Nvidia driver 520.56.06. This issue should not be closed.
