### ISSUE TITLE
version 5.10 now required

### ISSUE THREAD

**Issue by k-u-bux** [flathub/us.zoom.Zoom#324]
Upon start, zoom now says:

  Update Required
  Your app version needs to be 5.10.0 (2450) or higher to sign in.
  Please update to continue.

Consequently, the current flatpak is unusable.

**Comment by nedrichards** [comment]
Resolved by https://github.com/flathub/us.zoom.Zoom/commit/36008f3b678d71f2c7d121259006ae9ca31d94df
