### ISSUE TITLE
Screensharing is broken without GNOME

### ISSUE THREAD

**Issue by Stebalien** [flathub/us.zoom.Zoom#339]
When using flatpak with X, but without GNOME or KDE, Zoom screen sharing used to work perfectly. Now it fails with:

```
A backend call failed: No such interface “org.freedesktop.impl.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
Failed to close session implementation: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/portal/desktop/session/1_1083/zoomcast1”
```

Portals installed:

- xdg-desktop-portal
- xdg-desktop-portal-gnome
- xdg-desktop-portal-gtk

Version:

```
          ID: us.zoom.Zoom
         Ref: app/us.zoom.Zoom/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 5.11.0.3540
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 4.0 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: adae10c8af0d941f7c7832809f2f7825de0af519a4fde96097b3752b0cb98b5f
      Parent: 2ceb19fbf65f8d67b1f6de0ed90c7a850778fbce2cb83c51f8b1cd85c80dafdf
     Subject: Update zoom.tar.xz to 5.11.0.3540 (#337) (ccaa2aaf)
        Date: 2022-06-22 08:23:44 +0000
```

**Comment by nedrichards** [comment]
Can you test the latest commit? Where we pretend to be GNOME even if we're not there.

**Comment by Stebalien** [comment]
It doesn't fix it. Unfortunately, my problem is the inverse. I'm _not_ using Wayland, but Zoom keeps trying to use the ScreenCast protocol.

I've tried setting XDG_CURRENT_DESKTOP=i3 (using flatseal) to try to force Xorg screen sharing, but that didn't seem to do anything. Zoom still tries to use the ScreenCast API, which isn't implemented because I'm not using GNOME, KDE, or any wayland-based system.

**Comment by nedrichards** [comment]
Right, the screencast API isn't Wayland specific, it can work just as well on an X11 device to broker screen access without the app having to snoop windows. Generally though this sounds like an issue for the actual zoom developers - and if they want to make sure that systems have a screencast api implementation available to use the feature that's their call.

Feel free to reopen or suggest a PR if you discover a way that we can configure things that improves things for you.

**Comment by bayazidbh** [comment]
I've recently tested the screensharing on Nobara (Fedora 36) KDE - it does spawn the screensharing portal but after that it's stuck just loading for minutes (which, even if it loads eventually (which I don't know), is unacceptable in real meeting). It isn't a problem with my connection - I tried it with a natively installed Brave browser and I was able to share windows just fine.

Should I make a new issue, or something, and do you guys need more data?
