### ISSUE TITLE
Update of sign key required?

### ISSUE THREAD

**Issue by carhe** [flathub/us.zoom.Zoom#354]
There is an article on the Zoom support web pages saying that

> In November 2022, Zoom is retiring the current key pair used to sign the Zoom desktop client for Linux, which customers can use to validate the Zoom desktop client. Users must download the new public key before attempting to upgrade to version 5.12.6, otherwise they will be unable to install this update.

The full article can be found [here](https://support.zoom.us/hc/en-us/articles/9836712961165).

I am wondering if there is something to do for the user when using the flatpak version?

**Comment by nedrichards** [comment]
nothing to do here.
