### ISSUE TITLE
Missing QT5 libraries in the last version

### ISSUE THREAD

**Issue by gocram** [flathub/us.zoom.Zoom#367]
Hi,
last version (5.13.5.431) doesn't work because the Qt5 libraries are missing:
```
[📦 us.zoom.Zoom bin]$ ldd /app/extra/zoom/zoom.real 
...
	libQt5QuickWidgets.so.5 => not found
	libQt5Quick.so.5 => not found
	libQt5Widgets.so.5 => not found
	libQt5X11Extras.so.5 => not found
	libQt5Gui.so.5 => not found
	libQt5Qml.so.5 => not found
	libQt5Network.so.5 => not found
	libQt5DBus.so.5 => not found
	libQt5Core.so.5 => not found
...
```
or better, they have been moved in a sub-directory: /app/extra/zoom/Qt/lib

Could you please check ? Thanks

**Comment by sonicnkt** [comment]
Is there any way to get this working again?
I have to use the application for our corporate zoom server and currently i have to boot into windows to use it.

**Comment by linuxissuper** [comment]
> Is there any way to get this working again? I have to use the application for our corporate zoom server and currently i have to boot into windows to use it.

you could downgrade to the last working version (that's what I did)   
`sudo flatpak update --commit=2fc2ad91e216ee28705ce05ab6a9b72f3086b4f620fa0b004cc2d546d01f097e us.zoom.Zoom`

**Comment by sonicnkt** [comment]
@linuxissuper thank you very much, downgrade worked. This saved me from dualbooting today.
Btw how can someone get those previous commit string for downgrading?

**Comment by tadas-s** [comment]
@sonicnkt 

```
flatpak remote-info --log flathub us.zoom.Zoom
```

**Comment by tadas-s** [comment]
My observations with this:

1. Latest Fedora rpm downloaded from [zoom download page][1] works fine (tested on another machine, runs Fedora 37 like my main pc).
2. Downloaded `5.13.5.431` and `5.13.4.711` version zoom.tar.xz files. The folder layout is somewhat changed, some Qt shared libraries were moved around. But it's bit beyond my understanding how it affects launching of the flatpak version.

[1]: https://zoom.us/support/download

**Comment by ermshiperete** [comment]
I'm getting a similar error that seems to be related. `~/.zoom/logs/zoom_stdout_stderr.log` shows:

```
/app/extra/zoom/zoom.real: error while loading shared libraries: libgssapi_krb5.
so.2: cannot open shared object file: No such file or directory
```

**Comment by cirulls** [comment]
I confirm it works at my end after upgrading to 5.13.5.431, thanks for the swift action.
