### ISSUE TITLE
Weird video corruption when screen sharing

### ISSUE THREAD

**Issue by brittyazel** [flathub/us.zoom.Zoom#384]
Using Zoom 5.14.5 on GNOME 43 on Archlinux I am getting some strange video artifacts when trying to screen share. Unlike the other reports I've come across, the issue isn't I 'can't get the share to work, it's that the share is working but the video output is garbled. It's like  the whole screen is tilted diagonally and what you're seeing is offset rows of video. I've attached a video of what the output looks like, pardon how small it is as I could only capture the small preview from my end.

I'm using Wayland, and I've confirmed that WebRTC capture works perfectly fine for other programs. This seems to be something isolated to Zoom specifically.

EDIT: One interesting note is that screen sharing works perfectly on the browser version of Zoom on the same system, so this seems to be localized to either the Linux client or specifically the Flatpak'd Linux client.

![Screenshot from 2023-04-21 09-41-57](https://user-images.githubusercontent.com/3747347/233695769-1b8d4582-5fee-4ca9-9db6-cd34d735d8ba.png)

**Comment by ozdreamern** [comment]
For whatever it's worth, I just tested screen sharing under Wayland on Pop_OS 22.04 (gnome shell 42.5), and it was successful, in terms of presenting correctly on other participants' screens, although Zoom freezes when I click "stop sharing" (this has been the case through several Zoom versions, this is status quo ante for me).  My laptop has an Intel i7 Comet Lake + UHD graphics, btw.

**Comment by dbarbi1** [comment]
This looks like what has been reported here: https://community.zoom.com/t5/Meetings/Wayland-screen-sharing-broken-on-high-res-beyond-1080p-displays/m-p/73377

In my case, it is specific to the 21:9 screen resolution and zoom on wayland. Similar to you, the browser client works just fine.

**Comment by brittyazel** [comment]
@dbarbi1 yep, that's exactly my issue. Apparently anything other than 16:9 causes issues. I also use a 21:9 ultrawide.

Interesting to note is the web client works perfectly fine. So it's something internal, specific to the linux desktop client. I tried seeing if I had the same issue with the AUR version of Zoom, but for some reason I can't get that one to run at all.

**Comment by dbarbi1** [comment]
I get the same behavior from both the flatpak and fedora rpm package.

**Comment by brittyazel** [comment]
I reported this issue to upstream Zoom engineers, and they asked for a recording of the issue and any information I could provide their engineers. It turns out that I can only replicate the issue with 3440x1440 resolutions, and the others I tried (2560x1440, 2560x1080, 2048x1152, 1920x1440, 1920x1200, and 1920x1080) all worked just fine. So it seems less to do with the aspect ratio and more to do with that particular resolution. I don't have a monitor that goes higher so I can't test anything about WQHD unfortunately.

**Comment by brittyazel** [comment]
Just an update for everyone. I've been working with Zoom's engineering teams through one of their QA representatives. They cannot replicate this issue on their end, which is odd, but they've been sending me local test builds to try out and report back. So far, they have not fixed the issue, though temporarily they added a new issue where screen sharing would instantly crash the app, but fortunately they seem to have resolved whatever caused that. I'm hoping they can get to the root cause of this issue soon though!

**Comment by brittyazel** [comment]
This was fixed a while back. It was a weird issue with Zoom misunderstanding the screen's capabilities as exposed by Wayland.
