### ISSUE TITLE
Update required to sign in

### ISSUE THREAD

**Issue by Maltimore** [flathub/us.zoom.Zoom#387]
I currently can't use this app at all; it requires at least version 5.14.7 to sign in.

**Comment by geckolinux** [comment]
Hi there @muelli , I'm not seeing any newer Flatpak version.

**Comment by muelli** [comment]
There is one here: https://github.com/flathub/us.zoom.Zoom/pull/386
But nobody has checked yet whether it actually works.

**Comment by Maltimore** [comment]
@muelli how does one install from a pull request? I did a quick googling but didn't find the answer, maybe you could give me a pointer?
