### ISSUE TITLE
Google login is broken again

### ISSUE THREAD

**Issue by dac73** [flathub/us.zoom.Zoom#39]
I don't know with which version it broke, but I was logged out with the last update, and can't log back in. I'm getting: `Your login attempt was unsuccessful. Try again. If this occurs multiple times, contact IT support.`

Having the same problem on OpenSUSE Tumbleweed and Fedora Silverblue 31

**Comment by scoronado12** [comment]
Just caught this issue, running Arch Linux. Very unfortunate.

**Comment by abachm** [comment]
On Linux Mint 19.2 I tried to install both the latest zoom from deb package and from flathub and both have the problem of not being able to auth against google.
I can not confirm, but it might not be an issue with the zoom version on flathub, but a general zoom issue

**Comment by scoronado12** [comment]
@abachm Thanks for confirming with us, we may have to report this to Zoom support or something of that nature.

**Comment by scoronado12** [comment]
Just got in touch with Zoom support.

![image](https://user-images.githubusercontent.com/9601750/66443628-d45f4a80-ea0d-11e9-94d1-4d895ac37d9c.png)

**Comment by scoronado12** [comment]
Issue resolved after downloading the latest update.

**Comment by dac73** [comment]
Confirming it works now.
