### ISSUE TITLE
Update to version 2.0.123200.0405

### ISSUE THREAD

**Issue by l-sz** [flathub/us.zoom.Zoom#4]
Installation from flathub fails because the source file was updated and the size and sha256 sum changed. The latest release is version 2.0.123200.0405.

The new values for the x86 architecture:
sha256 sum: 7f9c52752ba2b86e696da09821bb61b7fb5b4fc369b82005a581d7e2ba50dcc5
size: 64623412

i386 architecture:
sha256 sum: a325257ea1211908001248ad349ba57b957cbad9e3cb2c097027b273ac4757a2
size: 40537804

It would be great to automatize updating this data in order to assure that the flatpak is always installable. Are there any plans to do this?

PS: Thanks for creating this flatpak!

**Comment by TingPing** [comment]
> It would be great to automatize updating this data in order to assure that the flatpak is always installable. Are there any plans to do this?

https://github.com/flathub/buildbot-config/issues/7

**Comment by nedrichards** [comment]
Fixed in https://github.com/flathub/us.zoom.Zoom/commit/197a0f3339c4efdb759acd856e17ebef00c2c8ba
