### ISSUE TITLE
Update to 5.16.10 is broken as screenshot has moved.

### ISSUE THREAD

**Issue by choffee** [flathub/us.zoom.Zoom#425]
• file-invalid          : <screenshot> failed to load [https://support.zoom.us/hc/article_attachments/115017677066/Screen_Shot_2017-11-19_at_6.34.49_PM.png]

https://github.com/flathub/us.zoom.Zoom/blob/1f2c488d97b5de2c428c29fbf6546e9200a92ee7/us.zoom.Zoom.appdata.xml#L25

Maybe this line needs removing or updating?

This is blocking #424

**Comment by muelli** [comment]
hrm. yeah. do you have a new URL?

**Comment by choffee** [comment]
Looks like they have had a big re-org.

Maybe this one: https://assets.zoom.us/images/en-us/desktop/generic/in-meeting/zoom-screen-share-preview.png

The other option would be just to remove that image.

**Comment by takluyver** [comment]
I've opened #426 to remove the failing URL.

[This screenshot](https://developers.zoom.us/img/nextImageExportOptimizer/meetingsdk-desktop-opt-640.WEBP) might be another possibility, but I don't know if .webp files work for this, and I think allowing it to build is higher priority than having more screenshots.
