### ISSUE TITLE
Zoom refuses to start after latest update

### ISSUE THREAD

**Issue by 0unknwn** [flathub/us.zoom.Zoom#437]
After the latest update (a7c23401) Zoom refuses to start on my 

- Fedora Silverblue (ublue) 39 

machine.

I was able to make it work again by reverting to the commit before (6241302e) with:

```
flatpak update --commit=786cd52f8219276edd0184f3c6fa0ca7041c3814369fe378dc068a0864b049a9 us.zoom.Zoom
```

To prevent it from getting updated automatically I also run:

```
flatpak mask us.zoom.Zoom
```

Then you have to run the following command to update it again, after this is fixed:

```
flatpak mask --remove us.zoom.Zoom
```

**Comment by theflu** [comment]
I am having the same issue on Ubuntu 22.04

```
$ flatpak info us.zoom.Zoom 

Zoom - Video Conferencing, Web Conferencing, Webinars, Screen Sharing

          ID: us.zoom.Zoom
         Ref: app/us.zoom.Zoom/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 5.17.1.1840
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 6.9 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 6706c80cba4a13af60d269900ab4c7f56568bcc6ce4bc4493bd6ec2f123f3be1
      Parent: 786cd52f8219276edd0184f3c6fa0ca7041c3814369fe378dc068a0864b049a9
     Subject: Update zoom.tar.xz to 5.17.1.1840 (a7c23401)
        Date: 2024-01-11 07:31:32 +0000
```

```
$ flatpak run --command=sh us.zoom.Zoom
[📦 us.zoom.Zoom /]$ zoom
(process:9934): GLib-CRITICAL **: 09:22:15.014: Failed to set scheduler settings: Operation not permitted
```

**Comment by muelli** [comment]
@abachm it looks like the newer version should be rolled back. Can you have a look?

**Comment by 0unknwn** [comment]
@PhoenixFossGR, have you tried to run this command?

`flatpak update --commit=786cd52f8219276edd0184f3c6fa0ca7041c3814369fe378dc068a0864b049a9 us.zoom.Zoom`

**Comment by matdave** [comment]
For anyone stumbling upon this, don't forget to `flatpak mask --remove us.zoom.Zoom` after this has been fixed, or you will be locked into an outdated version.

**Comment by milliams** [comment]
> I am encountering the following error: `Error: No current masked pattern matching us.zoom.Zoom`

You only need to do the `flatpak mask --remove us.zoom.Zoom` if you've previously done `flatpak mask us.zoom.Zoom`. The `mask` locks the version in place so a `flatpak update` doesn't go ahead and re-update the version of Zoom before this is fixed. _If_ you've `mask`ed it now, you'll need to remember to `mask --remove` in the future.

**Comment by stylerw** [comment]
Can confirm the same issue on Fedora Kinoite 39 with this latest version.  Flatpak Zoom crashes on launch after latest update.  Rolled back to an earlier commit and all is good, but this release is absolutely busted.

**Comment by droghio** [comment]
Can also confirm error with Rocky 9.1. Loaded `~/.zoom/logs` and got the following:

```
ZoomLauncher started.
Zoom path is: /app/extra/zoom
cmd line: 
Start subprocess: /app/extra/zoom/zoom sucessfully,  process pid: 3 
Can't load/home/droghio/.config/zoomus.conf
sh: line 1: pacmd: command not found
[13 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[13 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[13 preload-host-spawn-strategy] Warning: waitpid override ignores groups
                             Class      App      Lib Possible Culprit Flags
                resip::Connection      656      656 
                      resip::Data       36       36 
                 resip::DnsResult     1080     1080 
                   resip::Headers        1        1 
          resip::MsgHeaderScanner       40       40 
                resip::SipMessage     5224     5224 
         resip::TransportSelector      896      896 
                     resip::Tuple      128      128 
              resip::UdpTransport     1144     1144 
          resip::GenericIPAddress       28       28 

zoom started.
[27 zypak-sandbox] Failed to send spawn request to supervisor: Bad file descriptor (errno 9)
[0112/015235.597259:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Operation not permitted (1)
```

Just ran `flatpak update` thinking it was originally an outdated Nvidia platform but still no dice.

At first glance may be related to https://github.com/electron/forge/issues/2805 but haven't verified. Confirmed rolling back fixes the issue.

**Comment by 0unknwn** [comment]
I really wonder, why this was merged, as the problems with this build where discussed here: #429.

Maybe there should be a stricter policy with testing in this repo.

**Comment by muelli** [comment]
> Maybe there should be a stricter policy with testing in this repo.

well. I generally agree. And I am very careful when merging Zoom updates because I was eagerly merging to provide the latest and greatest to our users but then got bitten a few times by faulty updates. Now I'm very hesitant which also upsets a few users. Anyway, I guess that @abachm will be a bit more diligent the next time.

Oh, sorry that we broke your setup!

Speaking more broadly, I could imagine an automatic smoke-test to make sense. Apps on Flathub are all expected to spawn a windows that lasts for longer than, say, 10 seconds. I guess one could automate the task of launching an app and testing for the presence of a window.

**Comment by takluyver** [comment]
There's some details on #429 - the summary is that I think we need a newer Zypak to fix compatibility. I asked for a new release, but it doesn't seem to be happening quickly, so we may need to just build it from a commit.

It's really frustrating that the bot will open several PRs for the same release with no warning. #436 was merged after one user said it worked, when it was identical to #429, where two users had already said it crashes. :disappointed:

**Comment by danielebrox** [comment]
I'm using Fedora 40. Both dnf and flatpak methods crash on launch.
The only way to get it to work is to do what is suggested at the beginning of this thread. I have no idea what's going on.
