### ISSUE TITLE
Why are all files in the sandbox from 1 Jan 1970?

### ISSUE THREAD

**Issue by pgoodall** [flathub/us.zoom.Zoom#442]
I'm not sure if this is a problem or not, but I was about to close a terminal window where I had a shell inside the sandbox for the Zoom flatpak, and I noticed that almost all the last modified dates are 1 Jan 1970. I don't know if this would cause any problems or was an indication of a problem.

```shell
[📦 us.zoom.Zoom ~]$ ls -l /app/bin/
total 980
-rwxr-xr-x. 2 pete pete    162 Jan  1  1970 apply_extra
-rwxr-xr-x. 2 pete pete     26 Jan  1  1970 gvfs-trash
-rwxr-xr-x. 2 pete pete  18712 Jan  1  1970 notify-send
-rwxr-xr-x. 2 pete pete   1120 Jan  1  1970 zoom
-rwxr-xr-x. 2 pete pete    132 Jan  1  1970 zoom-wrapper.sh
-rwxr-xr-x. 2 pete pete 577368 Jan  1  1970 zypak-helper
-rwxr-xr-x. 2 pete pete 380288 Jan  1  1970 zypak-sandbox
lrwxrwxrwx. 1 pete pete     25 Jan 17 14:24 zypak-wrapper -> /app/bin/zypak-wrapper.sh
-rwxr-xr-x. 2 pete pete    285 Jan  1  1970 zypak-wrapper.sh
```

**Comment by takluyver** [comment]
I checked a couple of other Flatpaks and saw the same thing. January 1st 1970 is the zero point for the most common way of storing timestamps ([Unix time](https://en.wikipedia.org/wiki/Unix_time)), so you often see it where something wants to avoid storing the current time, e.g. to improve reproducibility.

So I'm pretty sure there's no issue here.

**Comment by pgoodall** [comment]
OK. I just wanted to make sure there wasn't something wrong. I get the whole beginning-of-unix-time thing. Thanks for looking at this more closely.
