### ISSUE TITLE
Can't join meeting from link if Zoom already running

### ISSUE THREAD

**Issue by takluyver** [flathub/us.zoom.Zoom#445]
One thing that I didn't include in my brief tests before #443 was merged: joining a Zoom meeting from a link. With Zoom 5.17.5.2543, this seems to be broken if the Zoom client is already running - the 'launch meeting' page opens in Firefox, but Zoom doesn't do anything, and clicking the 'Launch Meeting' button on the page also has no effect.

I can work around it by quitting Zoom (so the tray icon is gone) and then opening the page or clicking the button again.

I'm looking for clues on what's going wrong.

**Comment by muelli** [comment]
thanks for reporting the issue and providing a work around.

Do you happen to know whether this is also a problem for the non-flatpaked version?

**Comment by takluyver** [comment]
I don't know at present. It's an obvious thing to try, but I'm also not entirely sure how they interact if both apps are there claiming to handle `zoommtg://` URLs. And I need to use Zoom today, which puts a limit on my experimentation. :wink:

**Comment by jmcfarlane** [comment]
Am seeing the same (fc39)

**Comment by ManOfSex69** [comment]
I'm having the same issue on Fedora39.
I also tried the .tar.xz but the issue persisted.

**Comment by takluyver** [comment]
Thanks for testing that. That suggests that it's an issue with Zoom as a whole rather than the Flatpak packaging. If that is the case, the only thing I know of to do is post on the [Zoom community forums](https://community.zoom.com/t5/Meetings/bd-p/meetings) about the issue.

**Comment by takluyver** [comment]
I've just tested with the RPM version from [Zoom's download page](https://zoom.us/download), and it *does* work for me - I can use a link to join a meeting when Zoom is already running.

Using `strace` on that, I can see it's using a socket `/tmp/qtsingleapp-zoom-3e8`, and an associated lock file, to communicate from the new instance to the existing one. Googling points to the [QtSingleApp](https://github.com/qtproject/qt-solutions/tree/master/qtsingleapplication) library. I think that should work inside Flatpak, but it's not even trying to create the socket. :confused:

**Comment by takluyver** [comment]
I now seem to have it in a state where `flatpak run us.zoom.Zoom zoommtg://...` gets stuck, but starting a shell with `flatpak run --command=bash us.zoom.Zoom` and then launching `zoom zoommtg://...` in there works as expected. I don't know how those are different.

(I tried deleting my `~/.zoom` and `~/.var/app/us.zoom.Zoom` folders, to reset zoom as if I was installing it on a new machine. That seemed to solve the problem for a minute, but then it happened again.)

**Comment by kwyxz** [comment]
We have users reporting that SSO is broken again. Downgrading the flatpak to commit 04aaf2b043d0887115d5954ca5af88146d48a512021a0770e95b5cff5f7d00e9 solves the issue.

**Comment by maufl** [comment]
I had the same problem, downgrading to the previous commit fixed it!
`sudo flatpak update --commit=04aaf2b043d0887115d5954ca5af88146d48a512021a0770e95b5cff5f7d00e9 us.zoom.Zoom`

**Comment by heyakyra** [comment]
Is there no known workaround on an up-to-date flatpak install of Zoom? Am completely unable to log in still, at least on Fedora 39 and 49, Firefox flatpak and Chrome .rpm, but if I can get to a URL like `https://[company-subdomain].zoom.us/saml/mobile_success?token=[token string]`, then could that be manually translated into some `zoommtg://` URL to open?

**Comment by takluyver** [comment]
There seem to be multiple, possibly related issues. This thread is about joining meetings from links in the browser, for which the workaround seems to be to quit Zoom first and then open the link in the browser - it works as long as Zoom isn't already running.

If you're having issues logging in, look at e.g. #446 or #451.

I briefly looked into how the `zoommtg://` link is generated, but it's undocumented (probably deliberately) and the Javascript that does it is obfuscated. Whatever broke opening links seemed to come later, after the `zoommtg://` URL got to the operating system, so I didn't pursue digging into that.

**Comment by takluyver** [comment]
I think I've figured out what's going on. This is educated guesswork, but...

I mentioned before that there are two 'singleton' mechanisms at play: Chromium's SingletonSocket & a Qt-based qsingleapp, both working with Unix sockets. I think the Qt one is the one that actually works - the Chromium one is not normally in use, and doesn't work if you try to use it.

The way that Zoom uses Chromium, it looks for the SingletonSocket in a folder like `~/.zoom/data/cefcache/$PID/SingletonSocket`. Without Flatpak, each running process has a unique PID, and therefore will create its own SingletonSocket, effectively bypassing this singleton mechanism entirely. Then a later piece of the code uses the qtsingleapp mechanism instead.

But Flatpak puts Zoom in a PID namespace, so each time you launch Zoom it sees its own PID as a consistent small number (it seems to get 4 on my system). So it doesn't use a unique directory for SingletonSocket, but instead it sees the SingletonSocket from the previous process and writes a message to it - which doesn't actually work, but diverts it from using the qtsingleapp mechanism that does work.

Using `flatpak run --command=bash us.zoom.Zoom` and launching Zoom from 'inside' the sandbox appears to work because bash takes up an extra PID, so Zoom gets a different PID from when you run it without bash, and therefore doesn't see the socket.

If I'm right about this, I think it should be possible to work around it by removing the symlinked sockets before launching Zoom.

**Comment by takluyver** [comment]
#456 seems to work around this issue for me, but it would be good if other people can test it too. You can install the test version with:

```shell
flatpak install --user https://dl.flathub.org/build-repo/94766/us.zoom.Zoom.flatpakref
```

**Comment by fhausmann** [comment]
> #456 seems to work around this issue for me, but it would be good if other people can test it too. You can install the test version with:
> 
> ```shell
> flatpak install --user https://dl.flathub.org/build-repo/94766/us.zoom.Zoom.flatpakref
> ```

Nice fixes the issue for me. Thank you!
