### ISSUE TITLE
Unable to join Zoom meetings via browser links on Linux Mint 21.3

### ISSUE THREAD

**Issue by sudo-franko** [flathub/us.zoom.Zoom#449]
When attempting to join a Zoom meeting by clicking on a Zoom link within the Google Chrome browser, whether it's a scheduled meeting or not, the expected behavior is to be redirected to the waiting room or the meeting itself after clicking "Start Meeting" and then "Open with Zoom". However, on Linux Mint 21.3 with kernel version 5.15.0-97-generic, this action does not initiate any response from the Zoom application. The application fails to launch or redirect, leaving me unable to join the meeting. I'm using version 5.17.5 (2543).

**Comment by aasseman** [comment]
This fixed it for me: https://github.com/flathub/us.zoom.Zoom/issues/194#issuecomment-734461264

**Comment by sudo-franko** [comment]
It didn't work for me. It might be because I'm using the .deb version of Chrome. Still, thank you for your response.

**Comment by galloramiro** [comment]
This is still not working for me on Fedora
![Screenshot_20240327_090050](https://github.com/flathub/us.zoom.Zoom/assets/25160187/9edf8034-da7b-47b9-b54f-0776922c8c0f)

**Comment by DrYak** [comment]
sound similar to #446

**Comment by takluyver** [comment]
I think this is the same as #445, in which case it's hopefully solved by #456.
