### ISSUE TITLE
Can't join meetings without latest version of client 5.17.10

### ISSUE THREAD

**Issue by choffee** [flathub/us.zoom.Zoom#450]
There is a pull request #447  open which should fix this could this be pushed live please?

**Comment by choffee** [comment]
This now requires 5.17.11

**Comment by bluewww** [comment]
What is the process of getting a PR merged? Is there somewhere I can hellp? Seems to be pending for 2 weeks by now. I have to fall back to the deb version by now.

**Comment by muelli** [comment]
somebody needs to test whether the new version actually works. We've had some breakages in the past with prematurely published versions. You can test proposed versions and report back how well they work.

**Comment by bluewww** [comment]
I tried to do that earlier but the build in the PR 404'd

See 
https://dl.flathub.org/build-repo/88584/us.zoom.Zoom.flatpakref

**Comment by DrYak** [comment]
Could somebody with proper right retrigger the build 5.17.11 in POR #452 so we could test and confirm it?
Thanks!

**Comment by DrYak** [comment]
5.7.11 got merged, thanks!
