### ISSUE TITLE
Closing screen sharing freezes zoom (again)

### ISSUE THREAD

**Issue by lcrippa** [flathub/us.zoom.Zoom#485]
As previously was happening on linux with pipewire 1.2. This happens with the latest version of the flatpak (after update to zoom version 6.2.3.2056). Downgrading to flathub commit de80dc7f58e3aca63532b5c590c8ff21eeab18c87abfd2116c56e06bd1c9684b (zoom version 6.2.2.2028) fixes the issue.

**Comment by ksimuk** [comment]
https://github.com/flathub/us.zoom.Zoom/pull/484 this is the commit that broke screensharing, I do not think zoom app anyhow ready for "24.08" runtime until they fix the issue with pipewire compatibility,

**Comment by lcrippa** [comment]
Indeed building with 23.08 fixes the issue (even with the latest version of zoom). Could we perhaps revert #484 ?

**Comment by samy-k97** [comment]
Sorry for that! All of my testing was done on X.Org, so I haven't caught any of the issues that was on Wayland. I'll be more cautious and test both.

We can delay the introduction of 24.08 for a couple of months and maybe when Zoom decides to properly support pipewire.
