### ISSUE TITLE
Update to 24.08 runtime

### ISSUE THREAD

**Issue by F-i-f** [flathub/us.zoom.Zoom#496]
Zoom should be updated to the 24.08 runtime.

**Comment by muelli** [comment]
https://github.com/flathub/us.zoom.Zoom/commit/2675a27ce4b7745cf99e3e9dac64fac81052ae5f

https://github.com/flathub/us.zoom.Zoom/pull/484

**Comment by polter-rnd** [comment]
As per the latest feedback ([Solved: re: share screen linux wayland broken](https://community.zoom.com/t5/Zoom-Meetings/share-screen-linux-wayland-broken/m-p/184687/page/4)), the issue with pipewire >= 1.2 seems to be fixed in Zoom 6.2.10
