### ISSUE TITLE
ZoomLauncher: No such file or directory

### ISSUE THREAD

**Issue by tophneal** [flathub/us.zoom.Zoom#50]
Thanks for this! I almost gave up trying to get Zoom on aarch64. However, I cannot get the app to launch. Manjaro ARM on Pinebook Pro. This is the output:

```
$ flatpak run -v us.zoom.Zoom
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/topherneal/.local/share/flatpak
F: Opening user flatpak installation at path /home/topherneal/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/topherneal/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 4079305379
F: Allocated instance id 4060657129
F: Add defaults in dir /us/zoom/Zoom/
F: Add locks in dir /us/zoom/Zoom/
F: Allowing homedir access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Running 'bwrap --args 31 xdg-dbus-proxy --args=33'
F: Running 'bwrap --args 31 zoom'
/app/bin/zoom: line 2: /app/extra/zoom/ZoomLauncher: No such file or directory

```

**Comment by barthalion** [comment]
It's not being built for anything but x86_64. It's a mistake it was published for other architectures. I will keep it open so I don't forget to remove it.

You could technically get it to work if you install static qemu-user and pass `--arch=x86_64` to flatpak but it won't be native either.

**Comment by tophneal** [comment]
Bummer. I thought I had finally found what I was looking for after being redirected to the flatpak from another instance. Oh well, thanks for your reply and advice. I'll give it a shot, if it works well enough to sit in on a meeting, I'll be happy.
