### ISSUE TITLE
Zoom does not inhibit screen from locking

### ISSUE THREAD

**Issue by rombert** [flathub/us.zoom.Zoom#58]
I initially installed zoom using an RPM, then switched to the flatpak. What I noticed is that during a call with no keyboard/mouse input the screen will dim/blank. That did not happen with the RPM.

FWIW, I am using Gnome 3.34.

**Comment by muelli** [comment]
Hm. Yeah, happened to me, too.
I wonder whether the app uses the `org.gnome.SessionManager::Inhibit()` interface and whether the permissions are missing.

**Comment by FlorinPopaCodes** [comment]
I'm experiencing the same issue on archlinux. Works fine when installed via AUR, but not through flatpack.

**Comment by taaem** [comment]
Probably some dbus interface not properly exposed in the sandbox, btw the desktop agnostic way for screen inhibiting is: `org.freedesktop.ScreenSaver::Inhibit()`

**Comment by taaem** [comment]
Just checked, the skype flatpak uses:
 `        "--system-talk-name=org.freedesktop.login1",`
In their manifest, so here the right name for the bus name Zoom is using is needed.
(Probably their using the same one)

**Comment by kparal** [comment]
[VLC](https://github.com/flathub/org.videolan.VLC/blob/master/org.videolan.VLC.json) uses:
```
    "--talk-name=org.freedesktop.ScreenSaver",
```
So very likely this is exactly the permission we need. 

I see some inhibit options even in the mentioned `org.freedesktop.login1`, including inhibiting idle:
https://www.freedesktop.org/wiki/Software/systemd/logind/
But that dbus object is much more powerful, and I'm not sure we can give access to only some methods? I'd start by trying to give access to freedesktop screensaver first.

Can somebody please test?

**Comment by muelli** [comment]
Do we not have tooling to check what the sandboxed app tries use? Or rather what access flatpak denied? A bit like dbus-monitor, but tailored towards flatpak and permissions.
Then we can actually check what the app uses rather than making guesses.

**Comment by rombert** [comment]
> Can somebody please test?

Sorry, moved away from Zoom and can no longer test.

**Comment by taaem** [comment]
I tested it and Zoom uses:
```
    "--talk-name=org.freedesktop.ScreenSaver"
```

**Comment by muelli** [comment]
cool. thanks. How did you test?

**Comment by taaem** [comment]
@muelli I allowed zoom complete access to the dbus session bus with:
```
--sockets=session-bus
```
Then I ran 
```
dbus-monitor --session | grep -e Session -e Screen -e login
```
And then I could see when running zoom, that it calls out to `org.freedesktop.ScreenSaver`
I can provide the logs if someone is interested in that :shrug:
