### ISSUE TITLE
Only English

### ISSUE THREAD

**Issue by Yajo** [flathub/us.zoom.Zoom#59]
Well, I'm not sure if it's possible or not, but my colleagues told me they can see the app in other languages... Is it possible it's missing lang packs?

**Comment by yannick1974** [comment]
Hi @Yajo, you can change the language in the right click menu on the tray icon.

**Comment by Yajo** [comment]
I see no tray icon... I use GNOME.

**Comment by tvannahl** [comment]
Within the Zoom Client you need to click on your Profile Image (upper right corner), then go to "Help -> Switch Languages"

**Comment by Yajo** [comment]
Oh good! I would have never though of finding that under "help" :confounded: 

Thank you.
